# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_bgwrkR_wrappers", use_symbols = TRUE, package_name = "bgwrkR")

#' @docType package
#' @usage NULL
#' @useDynLib bgwrkR, .registration = TRUE
NULL

#' Represents a background running R script.
#' @export
BackgroundWorker <- new.env(parent = emptyenv())

BackgroundWorker$new <- function(script, schedule) .Call(wrap__BackgroundWorker__new, script, schedule)

#' @rdname BackgroundWorker
#' @usage NULL
#' @export
`$.BackgroundWorker` <- function (self, name) { func <- BackgroundWorker[[name]]; environment(func) <- environment(); func }

#' @export
`[[.BackgroundWorker` <- `$.BackgroundWorker`


# nolint end
